version: '3.3'

services:


  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - ./../server/:/app/server
    ports:
      - 8080:8080
    stdin_open: true

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    volumes:
      - ./../client/:/app/client
    stdin_open: true
    tty: true
    depends_on:
      - server
